//! The app icon: the revision graph planted as a parterre, seen from above. A tree of edges
//! grows from a root at the bottom and forks twice into four commits in the label colours, on
//! the slate of the dark theme. It is drawn in code so that the window icon and every packaged
//! asset come from one source: `examples/icon_assets.rs` writes the SVG, the PNGs, the Windows
//! `.ico` and the macOS `.icns` into `packaging/icon/`.
//!
//! Chosen on 2026-09-25 from four candidates; the prototype with all of them is on the branch
//! `prototype/app-icon` (`packaging/icon-prototype/index.html`).

/// Everything is designed in a 512 × 512 square.
const CANVAS: f32 = 512.0;
/// Corner radius of the tile: the 22.37 % of the side that macOS uses for its rounded squares.
const TILE_RADIUS: f32 = 114.5;
const EDGE_WIDTH: f32 = 28.0;
/// Width of the ring around every node, in a colour that stands out from both the node and
/// the tile.
const RING: f32 = 8.0;

/// How far macOS insets an app icon: the rounded square fills 824 of 1024 points, the rest is
/// transparent margin. Used for the `.icns`.
pub const MACOS_INSET: f32 = 100.0 / 1024.0;

type Rgb = [u8; 3];
/// Slate, the dark theme's canvas.
const TILE: Rgb = [0x24, 0x30, 0x38];
/// Hedge green.
const EDGE: Rgb = [0x4c, 0x9a, 0x4a];
/// Cream, for the rings.
const INK: Rgb = [0xf6, 0xf1, 0xe7];
/// Lavender, the app's colour for commits without a label.
const PLAIN: Rgb = [0xe6, 0xe6, 0xff];
/// The label colours: current branch, local branch, remote branch, tag.
const TIPS: [Rgb; 4] = [
    [0xc8, 0x00, 0x00],
    [0x00, 0xc8, 0x00],
    [0xff, 0xdc, 0xaa],
    [0xff, 0xe6, 0x00],
];

type P = (f32, f32);
/// A cubic Bézier: start, two control points, end.
type Cubic = [P; 4];

const ROOT: (P, f32) = ((256.0, 390.0), 30.0);
const FORKS: [(P, f32); 2] = [((156.0, 236.0), 18.0), ((356.0, 236.0), 18.0)];
const TIP_Y: f32 = 132.0;
const TIP_X: [f32; 4] = [106.0, 206.0, 306.0, 406.0];
const TIP_RADIUS: f32 = 40.0;

/// The edges, as the app draws them: out of the bottom centre of a node, into the top centre
/// of the next, bending only in between.
const EDGES: [Cubic; 7] = [
    [
        (256.0, 390.0),
        (256.0, 362.0),
        (256.0, 332.0),
        (256.0, 304.0),
    ],
    [
        (256.0, 304.0),
        (256.0, 268.0),
        (156.0, 272.0),
        (156.0, 236.0),
    ],
    [
        (256.0, 304.0),
        (256.0, 268.0),
        (356.0, 272.0),
        (356.0, 236.0),
    ],
    [
        (156.0, 236.0),
        (156.0, 190.0),
        (106.0, 178.0),
        (106.0, 132.0),
    ],
    [
        (156.0, 236.0),
        (156.0, 190.0),
        (206.0, 178.0),
        (206.0, 132.0),
    ],
    [
        (356.0, 236.0),
        (356.0, 190.0),
        (306.0, 178.0),
        (306.0, 132.0),
    ],
    [
        (356.0, 236.0),
        (356.0, 190.0),
        (406.0, 178.0),
        (406.0, 132.0),
    ],
];

/// Every node with its radius and fill: root, forks, then the four tips.
fn nodes() -> impl Iterator<Item = (P, f32, Rgb)> {
    std::iter::once((ROOT.0, ROOT.1, PLAIN))
        .chain(FORKS.iter().map(|&(c, r)| (c, r, PLAIN)))
        .chain(
            TIP_X
                .iter()
                .zip(TIPS)
                .map(|(&x, color)| ((x, TIP_Y), TIP_RADIUS, color)),
        )
}

/// The icon as `size` × `size` straight-alpha RGBA, the tile filling the square.
pub fn render(size: u32) -> Vec<u8> {
    render_inset(size, 0.0)
}

/// Like [`render`], with the tile scaled into the square left after a transparent margin of
/// `inset` × `size` on every side (see [`MACOS_INSET`]).
pub fn render_inset(size: u32, inset: f32) -> Vec<u8> {
    let mut r = Raster::new(size, inset);
    r.paint(TILE, (0.0, 0.0, CANVAS, CANVAS), |x, y| {
        let cx = x.clamp(TILE_RADIUS, CANVAS - TILE_RADIUS);
        let cy = y.clamp(TILE_RADIUS, CANVAS - TILE_RADIUS);
        (x - cx).powi(2) + (y - cy).powi(2) <= TILE_RADIUS * TILE_RADIUS
    });
    for cubic in &EDGES {
        r.cubic(EDGE, cubic, EDGE_WIDTH);
    }
    for (c, radius, color) in nodes() {
        r.circle(INK, c, radius + RING / 2.0);
        r.circle(color, c, radius - RING / 2.0);
    }
    r.finish()
}

/// The icon as an SVG document, drawn from the same tables as [`render`].
pub fn svg() -> String {
    let hex = |c: Rgb| format!("#{:02x}{:02x}{:02x}", c[0], c[1], c[2]);
    let mut s = String::new();
    s.push_str(
        "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\" width=\"512\" height=\"512\">\n",
    );
    // No "--" in here: XML forbids it inside a comment.
    s.push_str("<!-- Generated by crates/parterre-core/examples/icon_assets.rs ");
    s.push_str("from crates/parterre-core/src/icon.rs; edit the source, not this file. -->\n");
    s.push_str(&format!(
        "<rect width=\"512\" height=\"512\" rx=\"{TILE_RADIUS}\" fill=\"{}\"/>\n",
        hex(TILE)
    ));
    s.push_str(&format!(
        "<g fill=\"none\" stroke=\"{}\" stroke-width=\"{EDGE_WIDTH}\" stroke-linecap=\"round\">\n",
        hex(EDGE)
    ));
    for [a, b, c, d] in &EDGES {
        s.push_str(&format!(
            "  <path d=\"M{},{} C{},{} {},{} {},{}\"/>\n",
            a.0, a.1, b.0, b.1, c.0, c.1, d.0, d.1
        ));
    }
    s.push_str("</g>\n");
    s.push_str(&format!(
        "<g stroke=\"{}\" stroke-width=\"{RING}\">\n",
        hex(INK)
    ));
    for ((x, y), radius, color) in nodes() {
        s.push_str(&format!(
            "  <circle cx=\"{x}\" cy=\"{y}\" r=\"{radius}\" fill=\"{}\"/>\n",
            hex(color)
        ));
    }
    s.push_str("</g>\n</svg>\n");
    s
}

/// Subsamples per pixel and axis. Shapes are painted opaquely at this resolution and the
/// result is box-filtered down, which anti-aliases every edge and joins overlapping shapes
/// of one colour without seams.
const SS: u32 = 4;

/// A canvas at `SS` × the output resolution, addressed in design coordinates.
struct Raster {
    size: u32,
    /// Side of the supersampled buffer.
    n: u32,
    /// Design units to subpixels.
    scale: f32,
    /// Subpixel of design (0, 0).
    offset: f32,
    buf: Vec<[u8; 4]>,
}

impl Raster {
    fn new(size: u32, inset: f32) -> Self {
        let n = size * SS;
        let scale = n as f32 * (1.0 - 2.0 * inset) / CANVAS;
        Self {
            size,
            n,
            scale,
            offset: n as f32 * inset,
            buf: vec![[0; 4]; (n * n) as usize],
        }
    }

    /// Paints `color` on every subpixel inside the design-space box `(x0, y0, x1, y1)` whose
    /// centre satisfies `inside`.
    fn paint(
        &mut self,
        color: Rgb,
        (x0, y0, x1, y1): (f32, f32, f32, f32),
        inside: impl Fn(f32, f32) -> bool,
    ) {
        let to_sub = |d: f32| d * self.scale + self.offset;
        let lo = |d: f32| (to_sub(d).floor().max(0.0)) as u32;
        let hi = |d: f32| (to_sub(d).ceil().max(0.0) as u32).min(self.n);
        let px = [color[0], color[1], color[2], 255];
        for sy in lo(y0)..hi(y1) {
            let y = (sy as f32 + 0.5 - self.offset) / self.scale;
            for sx in lo(x0)..hi(x1) {
                let x = (sx as f32 + 0.5 - self.offset) / self.scale;
                if inside(x, y) {
                    self.buf[(sy * self.n + sx) as usize] = px;
                }
            }
        }
    }

    fn circle(&mut self, color: Rgb, (cx, cy): P, r: f32) {
        self.paint(color, (cx - r, cy - r, cx + r, cy + r), |x, y| {
            (x - cx).powi(2) + (y - cy).powi(2) <= r * r
        });
    }

    /// A line from `a` to `b` with round ends.
    fn segment(&mut self, color: Rgb, a: P, b: P, width: f32) {
        let (dx, dy) = (b.0 - a.0, b.1 - a.1);
        let len2 = (dx * dx + dy * dy).max(1e-6);
        let h = width / 2.0;
        let bbox = (
            a.0.min(b.0) - h,
            a.1.min(b.1) - h,
            a.0.max(b.0) + h,
            a.1.max(b.1) + h,
        );
        self.paint(color, bbox, |x, y| {
            let t = (((x - a.0) * dx + (y - a.1) * dy) / len2).clamp(0.0, 1.0);
            let (ex, ey) = (a.0 + t * dx - x, a.1 + t * dy - y);
            ex * ex + ey * ey <= h * h
        });
    }

    /// A stroked cubic Bézier with round ends, as a chain of short segments.
    fn cubic(&mut self, color: Rgb, [p0, p1, p2, p3]: &Cubic, width: f32) {
        const STEPS: usize = 32;
        let at = |t: f32| {
            let u = 1.0 - t;
            let (a, b, c, d) = (u * u * u, 3.0 * u * u * t, 3.0 * u * t * t, t * t * t);
            (
                a * p0.0 + b * p1.0 + c * p2.0 + d * p3.0,
                a * p0.1 + b * p1.1 + c * p2.1 + d * p3.1,
            )
        };
        let mut prev = at(0.0);
        for i in 1..=STEPS {
            let next = at(i as f32 / STEPS as f32);
            self.segment(color, prev, next, width);
            prev = next;
        }
    }

    /// Box-filters the buffer down to the output size. Transparent subpixels are black with
    /// zero alpha, so the plain sum is a premultiplied average; it is unpremultiplied at the
    /// end.
    fn finish(self) -> Vec<u8> {
        let mut out = Vec::with_capacity((self.size * self.size * 4) as usize);
        for y in 0..self.size {
            for x in 0..self.size {
                let mut sum = [0u32; 4];
                for sy in y * SS..(y + 1) * SS {
                    for sx in x * SS..(x + 1) * SS {
                        let p = self.buf[(sy * self.n + sx) as usize];
                        for (s, v) in sum.iter_mut().zip(p) {
                            *s += v as u32;
                        }
                    }
                }
                let alpha = sum[3];
                if alpha == 0 {
                    out.extend([0, 0, 0, 0]);
                } else {
                    out.extend(sum[..3].iter().map(|&c| (c * 255 / alpha) as u8));
                    out.push((alpha / (SS * SS)) as u8);
                }
            }
        }
        out
    }
}

/// A Windows `.ico` holding `images`: `(side, bytes)` pairs where the bytes are either a PNG
/// or a DIB from [`ico_dib`]. Sides of 256 are stored as 0, as the format requires.
pub fn ico(images: &[(u32, Vec<u8>)]) -> Vec<u8> {
    let mut out = Vec::new();
    out.extend(0u16.to_le_bytes()); // reserved
    out.extend(1u16.to_le_bytes()); // type: icon
    out.extend((images.len() as u16).to_le_bytes());
    let mut offset = 6 + 16 * images.len() as u32;
    for (side, data) in images {
        let dim = if *side >= 256 { 0 } else { *side as u8 };
        out.extend([dim, dim, 0, 0]); // width, height, palette size, reserved
        out.extend(1u16.to_le_bytes()); // colour planes
        out.extend(32u16.to_le_bytes()); // bits per pixel
        out.extend((data.len() as u32).to_le_bytes());
        out.extend(offset.to_le_bytes());
        offset += data.len() as u32;
    }
    for (_, data) in images {
        out.extend_from_slice(data);
    }
    out
}

/// A 32-bit BGRA device-independent bitmap with the AND mask, as stored inside an `.ico`, from
/// straight-alpha RGBA of `side` × `side` pixels. Every size below 256 is stored this way; PNG
/// entries are only safe at 256.
pub fn ico_dib(side: u32, rgba: &[u8]) -> Vec<u8> {
    assert_eq!(rgba.len(), (side * side * 4) as usize);
    let mask_row = side.div_ceil(32) * 4; // bytes per row of the 1-bit mask, padded to 32 bits
    let mut out = Vec::new();
    // BITMAPINFOHEADER; the height counts both the colour bitmap and the mask.
    out.extend(40u32.to_le_bytes());
    out.extend((side as i32).to_le_bytes());
    out.extend((side as i32 * 2).to_le_bytes());
    out.extend(1u16.to_le_bytes()); // planes
    out.extend(32u16.to_le_bytes()); // bits per pixel
    out.extend(0u32.to_le_bytes()); // BI_RGB, uncompressed
    out.extend((side * side * 4 + mask_row * side).to_le_bytes());
    out.extend([0u8; 16]); // resolution and palette fields, unused
    // Colour rows, bottom-up, BGRA.
    for y in (0..side).rev() {
        for x in 0..side {
            let p = ((y * side + x) * 4) as usize;
            out.extend([rgba[p + 2], rgba[p + 1], rgba[p], rgba[p + 3]]);
        }
    }
    // Mask rows, bottom-up: a set bit means transparent, for readers that ignore alpha.
    for y in (0..side).rev() {
        let mut row = vec![0u8; mask_row as usize];
        for x in 0..side {
            if rgba[((y * side + x) * 4 + 3) as usize] == 0 {
                row[(x / 8) as usize] |= 0x80 >> (x % 8);
            }
        }
        out.extend(row);
    }
    out
}

/// A macOS `.icns` from `(type, png)` chunks, e.g. `(*b"ic08", png_256)`.
pub fn icns(chunks: &[([u8; 4], Vec<u8>)]) -> Vec<u8> {
    let total = 8 + chunks.iter().map(|(_, d)| 8 + d.len()).sum::<usize>();
    let mut out = Vec::with_capacity(total);
    out.extend(b"icns");
    out.extend((total as u32).to_be_bytes());
    for (kind, data) in chunks {
        out.extend(kind);
        out.extend((8 + data.len() as u32).to_be_bytes());
        out.extend_from_slice(data);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn alpha(px: &[u8], size: u32, x: u32, y: u32) -> u8 {
        px[((y * size + x) * 4 + 3) as usize]
    }

    #[test]
    fn tile_has_transparent_corners_and_an_opaque_middle() {
        let size = 64;
        let px = render(size);
        assert_eq!(px.len(), (size * size * 4) as usize);
        assert_eq!(alpha(&px, size, 0, 0), 0);
        assert_eq!(alpha(&px, size, size - 1, size - 1), 0);
        assert_eq!(alpha(&px, size, size / 2, size / 2), 255);
        assert_eq!(
            alpha(&px, size, 0, size / 2),
            255,
            "the tile touches the sides"
        );
    }

    #[test]
    fn inset_leaves_a_transparent_margin() {
        let size = 64;
        let px = render_inset(size, MACOS_INSET);
        assert!((0..size).all(|x| alpha(&px, size, x, 0) == 0));
        assert!((0..size).all(|y| alpha(&px, size, 0, y) == 0));
        assert_eq!(alpha(&px, size, size / 2, size / 2), 255);
    }

    #[test]
    fn shape_is_symmetric() {
        let size = 128;
        let px = render(size);
        for y in 0..size {
            for x in 0..size / 2 {
                let (a, b) = (alpha(&px, size, x, y), alpha(&px, size, size - 1 - x, y));
                assert!(a.abs_diff(b) <= 2, "alpha at ({x}, {y}): {a} vs {b}");
            }
        }
    }

    #[test]
    fn tips_are_in_label_colours() {
        let size = 512;
        let px = render(size);
        for (x, color) in TIP_X.iter().zip(TIPS) {
            let p = ((TIP_Y as u32 * size + *x as u32) * 4) as usize;
            assert_eq!(&px[p..p + 3], &color);
        }
    }

    #[test]
    fn svg_lists_every_shape() {
        let s = svg();
        assert_eq!(s.matches("<path ").count(), EDGES.len());
        assert_eq!(s.matches("<circle ").count(), 7);
        assert!(s.contains("rx=\"114.5\""));
        // Only the comment delimiters may contain "--"; XML forbids it inside a comment.
        assert_eq!(s.matches("--").count(), 2);
    }

    #[test]
    fn ico_layout() {
        let a = ico_dib(16, &render(16));
        assert_eq!(a.len(), 40 + 16 * 16 * 4 + 4 * 16);
        let b = vec![0x89, b'P', b'N', b'G'];
        let file = ico(&[(16, a.clone()), (256, b.clone())]);
        assert_eq!(&file[..6], &[0, 0, 1, 0, 2, 0]);
        assert_eq!(file[6], 16, "width of the first entry");
        assert_eq!(file[22], 0, "256 is stored as 0");
        let offset = |i: usize| {
            u32::from_le_bytes(file[6 + 16 * i + 12..6 + 16 * i + 16].try_into().unwrap()) as usize
        };
        assert_eq!(offset(0), 6 + 32);
        assert_eq!(offset(1), 6 + 32 + a.len());
        assert_eq!(&file[offset(1)..], &b[..]);
    }

    #[test]
    fn icns_layout() {
        let file = icns(&[(*b"ic08", vec![1, 2, 3])]);
        assert_eq!(&file[..4], b"icns");
        assert_eq!(
            u32::from_be_bytes(file[4..8].try_into().unwrap()) as usize,
            file.len()
        );
        assert_eq!(&file[8..12], b"ic08");
        assert_eq!(u32::from_be_bytes(file[12..16].try_into().unwrap()), 11);
    }
}
